#!/bin/bash

USER=`id -u`
X_SOCKET=/tmp/.X11-unix
CP_VOLUME=crashplan_data
CP_SERVICE=dockercrashplan_service_1

ARGS="--rm -it --link $CP_SERVICE:service -u $UID -v $X_SOCKET:$X_SOCKET -e DISPLAY=$DISPLAY --volumes-from $CP_VOLUME"

docker run $ARGS crashplan_desktop
